const mongoose = require('mongoose');
const Schema = mongoose.Schema({
    vendorId:{type:mongoose.Schema.Types.ObjectId,required:true},
    timing:{
        monday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        tuesday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        wednesday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        thursday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        friday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        saturday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        },
        sunday:{
            open:{
                type:String
            },
            close:{
                type:String
            },
            isClose:{
                type:Boolean,
                default:true
            }
        }
    }
})
module.exports = mongoose.model('VendorTiming',Schema)